### PR TITLE
update source to crossplane-contrib/provider-upjet-mysql

### PR DESCRIPTION
**Pull request by jbw976**
### Description of your changes

This PR updates the source code references to point to this providers new home in `crossplane-contrib/provider-upjet-mysql`.

Most of this PR is entirely a find/replace for `jellysmack-tech/provider-mysql` to `crossplane-contrib/provider-upjet-mysql`

The API group/versions have not been updated at all, so the CRDs do not change. There should be no specific migration needed for end users beyond changing the package's `spec.package`, similar to what's described in https://github.com/crossplane/crossplane/discussions/5435#discussioncomment-10732835.

I have:

- [x] Read and followed Crossplane's [contribution process].
- [x] Run `make reviewable test` to ensure this PR is ready for review.

### How has this code been tested

I have run `make build`, `make generate`, and `make reviewable`.

I saw some errors in `make reviewable` locally, but everything passed OK in CI. Perhaps there's a version mismatch between local and CI.

[contribution process]: https://git.io/fj2m9

### CODE REVIEW

**Comment by jbw976** [comment]
Oh nice, all checks on this PR passed (lint, test, etc.), so that's a good sign! 🟢

**Comment by mcanevet** [comment]
@jbw976 could you please use [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) convention for the subject of your commit so that [release-please](https://github.com/googleapis/release-please) properly compute the next version number?

**Comment by jbw976** [comment]
Good idea @mcanevet! I have amended the commit to use conventional commits format. I landed on `refactor!: ...` but let me know if you have an idea for a more suitable scope, and if you think the breaking changes indicator is not needed. While the APIs/CRDs that are installed into the control plane are not changing, the module change would impact anyone choosing to import this module 🤓

**Comment by mcanevet** [comment]
@jbw976 I think `refactor!:` is a good choice. Can I merge this?

**Comment by jbw976** [comment]
yes please! approve and merge if you're good with it! then I'll get publishing working in main after we get a CI run there. thank you 🙇‍♂️

**Pull request merged**
